abstract class BlockchainConstants {
  static const String contractName = 'EthereumTcc';
  static const String projectName = 'Ethernium';
  static const String descriptionOfProject = 'DApp de herança cripto';
  static const String urlProject =
      'https://github.com/FelipeLemosBellini/tcc_heranca';
  static const String addressSmartContract =
      '0x097CF3797fCfBaC61c64465345b0ffc48b34263e';
  static const String chainId = 'eip155:11155111';
  static const String nameChain = 'Sepolia';
  static const String currency = 'ETH';
  static const String rpcUrl = 'https://1rpc.io/sepolia';
  static const String explorerUrl = 'https://sepolia.etherscan.io/';
  static const String abi = '[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"testator","type":"address"},{"indexed":false,"internalType":"uint256","name":"grossAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"feeAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"netAmount","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"testator","type":"address"}],"name":"VaultCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"testator","type":"address"},{"indexed":false,"internalType":"address[]","name":"recipients","type":"address[]"},{"indexed":false,"internalType":"uint256[]","name":"amounts","type":"uint256[]"}],"name":"VaultDistributed","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"testator","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Withdraw","type":"event"},{"inputs":[],"name":"createVault","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"depositETH","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"testator","type":"address"},{"internalType":"address[]","name":"recipients","type":"address[]"},{"internalType":"uint256[]","name":"amounts","type":"uint256[]"}],"name":"distributeVault","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"myVault","outputs":[{"components":[{"internalType":"uint256","name":"balances","type":"uint256"}],"internalType":"struct EthereumTcc.VaultView","name":"v","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"showFees","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"testator","type":"address"}],"name":"vaultBalance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"withdrawETH","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"beneficiary","type":"address"}],"name":"withdrawFees","outputs":[],"stateMutability":"nonpayable","type":"function"},{"stateMutability":"payable","type":"receive"}]';
}
